### PR TITLE
[Makefile] Add VSCode target!

### PR DESCRIPTION
**Pull request by yartem**
Project's storage directory mounted to the job serving VS Code Server.

image

Multiple extensions supported, including:
- [Remote debugging](https://code.visualstudio.com/docs/editor/debugging),
- [Connect to remote Docker host](https://code.visualstudio.com/docs/remote/containers) to develop right inside it,
- [Path auto-completion](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense),
- [Python auto-completion](https://marketplace.visualstudio.com/items?itemName=ms-python.python) and [here](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)

### CODE REVIEW

**Comment by mariyadavydova** [comment]
Can you please explain how this feature works?

I see that you run a job with some specific Docker image. I assume that you can connect to this job via VS Code. But how does this target help to debug my ML code, which requires another environment (with all that stuff from 'requirements.txt')?

**Comment by yartem** [comment]
> I assume that you can connect to this job via VS Code.

No. This job starts VS Code in your browser with code mounted directly from Storage. Try it, it's cool! :smile:

**Comment by mariyadavydova** [comment]
I tried. I ran `make setup`, then `make vscode`. I've got the same several times:

```
Status: pending Creating
Status: pending Scheduling
Status: failed Error (fixuid: exec: "/usr/local/bin/code-server": stat /usr/local/bin/code-server: no such file or directory
)
```

I'm not sure if that's a cluster issue (`neuro-public`) or a code issue. Please take a look.

**Comment by yartem** [comment]
> I've got the same several times
Thank you! indeed, they changed image's internals we rely on (`--entrypoint` to over-write image's USER [to be able to write](https://github.com/neuromation/platform-api/issues/1096) to the mounted directory). I fixed the image version, should be working now.

**Comment by yartem** [comment]
Note: AWS also has its own cloud-based IDE working from the browser: 
https://aws.amazon.com/cloud9/

**Comment by yartem** [comment]
Look! AWS' IDE has already set up `aws` -- so we can have `neuro` set up in vscode job. And I think we should consider having a button on website.
image

**Comment by yartem** [comment]
TODO: Need to use base image

**Comment by yartem** [comment]
vscode would turn into a fully functional web-based IDE if run from base image:
1. you edit code from your web browser directly on the storage
2. in vscode terminal, you run `make train-local` and debug your code without any port-forwarding

**Comment by yartem** [comment]
Closing in favour of the [Web Button](https://github.com/neuromation/platform-pipelines/pull/41)

**Comment by yartem** [comment]
Will be added as web-button

**Pull request closed without merging**
